/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekstack;

/**
 *
 * @author Robbi Nanda
 */
import java.util.*;
public class Volume extends javax.swing.JFrame {
    
    
static String [] Gambar = {"/projekstack/1.png","/projekstack/2.png","/projekstack/3.png",
                            "/projekstack/4.png","/projekstack/5.png","/projekstack/6.png"};
static String [] Volume = new String [6];
static int topGambar=0;
    

public void pushVolume()
    {
          
        if (topGambar==0){
            Volume[topGambar]=Gambar[topGambar]; 
            vol1.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
        }
        else if (topGambar==1){
            Volume[topGambar]=Gambar[topGambar]; 
            vol2.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
        }
        else if (topGambar==2){
            Volume[topGambar]=Gambar[topGambar];  
            vol3.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
        }
        else if (topGambar==3){
            Volume[topGambar]=Gambar[topGambar]; 
            vol4.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
        }
        else if (topGambar==4){
            Volume[topGambar]=Gambar[topGambar]; 
            vol5.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
        }
        else if (topGambar==5){
            Volume[topGambar]=Gambar[topGambar]; 
            vol6.setIcon(new javax.swing.ImageIcon(getClass().getResource(Volume[topGambar])));
 
        }
        
    }
public void pickVolume()
    {
          
        if (topGambar==6){
           Volume[topGambar-1]=(null);  
            vol6.setIcon(null);
        }
        else if (topGambar==5){
            Volume[topGambar-1]=(null); 
            vol5.setIcon(null);
        }
        else if (topGambar==4){
            Volume[topGambar-1]=(null); 
            vol4.setIcon(null);
        }
        else if (topGambar==3){
            Volume[topGambar-1]=(null);
            vol3.setIcon(null);
        }
        else if (topGambar==2){
            Volume[topGambar-1]=(null);
            vol2.setIcon(null);
        }
        else if (topGambar==1){
            Volume[topGambar-1]=(null);
            vol1.setIcon(null);
        }
        
    }


    /**
     * Creates new form Volume
     */
    public Volume() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonUp = new javax.swing.JButton();
        ButtonDown = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        v1 = new javax.swing.JPanel();
        vol1 = new javax.swing.JLabel();
        v2 = new javax.swing.JPanel();
        vol2 = new javax.swing.JLabel();
        v3 = new javax.swing.JPanel();
        vol3 = new javax.swing.JLabel();
        v4 = new javax.swing.JPanel();
        vol4 = new javax.swing.JLabel();
        v5 = new javax.swing.JPanel();
        vol5 = new javax.swing.JLabel();
        v6 = new javax.swing.JPanel();
        vol6 = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonUp.setText("Up");
        ButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 60, -1));

        ButtonDown.setText("Down");
        ButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDownActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekstack/subwoofer_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projekstack/medium_volume_filled_50px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        v1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v1Layout = new javax.swing.GroupLayout(v1);
        v1.setLayout(v1Layout);
        v1Layout.setHorizontalGroup(
            v1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v1Layout.setVerticalGroup(
            v1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 84, 40));

        v2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v2Layout = new javax.swing.GroupLayout(v2);
        v2.setLayout(v2Layout);
        v2Layout.setHorizontalGroup(
            v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v2Layout.setVerticalGroup(
            v2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 84, 40));

        v3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v3Layout = new javax.swing.GroupLayout(v3);
        v3.setLayout(v3Layout);
        v3Layout.setHorizontalGroup(
            v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v3Layout.setVerticalGroup(
            v3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 84, 40));

        v4.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v4Layout = new javax.swing.GroupLayout(v4);
        v4.setLayout(v4Layout);
        v4Layout.setHorizontalGroup(
            v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol4, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v4Layout.setVerticalGroup(
            v4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 84, 40));

        v5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v5Layout = new javax.swing.GroupLayout(v5);
        v5.setLayout(v5Layout);
        v5Layout.setHorizontalGroup(
            v5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v5Layout.setVerticalGroup(
            v5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 84, 40));

        v6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout v6Layout = new javax.swing.GroupLayout(v6);
        v6.setLayout(v6Layout);
        v6Layout.setHorizontalGroup(
            v6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );
        v6Layout.setVerticalGroup(
            v6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vol6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 84, 40));

        Info.setBackground(new java.awt.Color(255, 255, 255));
        Info.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        Info.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpActionPerformed
        // TODO add your handling code here:
        if (topGambar>=6){
        Info.setText("Volume Max!");
    }
          
    else {
        Info.setText(null);
        pushVolume();
        topGambar++;
        
        
    }
    }//GEN-LAST:event_ButtonUpActionPerformed

    private void ButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDownActionPerformed
        // TODO add your handling code here:
        if (topGambar<=0){
        Info.setText("Volume Mati");
    }
          
    else {
        Info.setText(null);
        pickVolume();
        topGambar--;
    }
    }//GEN-LAST:event_ButtonDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDown;
    private javax.swing.JButton ButtonUp;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel v1;
    private javax.swing.JPanel v2;
    private javax.swing.JPanel v3;
    private javax.swing.JPanel v4;
    private javax.swing.JPanel v5;
    private javax.swing.JPanel v6;
    private javax.swing.JLabel vol1;
    private javax.swing.JLabel vol2;
    private javax.swing.JLabel vol3;
    private javax.swing.JLabel vol4;
    private javax.swing.JLabel vol5;
    private javax.swing.JLabel vol6;
    // End of variables declaration//GEN-END:variables
}
